### ISSUE TITLE
Cannot add U2F device 

### ISSUE THREAD

**Issue by vonProteus** [nextcloud/twofactor_u2f#690]
### Expected behaviour
i want to add u2f key

### Actual behaviour
i cannot 
```
{
   "reqId":"YzepTr91PibXfDlmLO82",
   "level":3,
   "time":"2020-03-30T16:59:53+00:00",
   "remoteAddr":"10.0.19.80",
   "user":"vonProteus",
   "app":"index",
   "method":"POST",
   "url":"/apps/twofactor_u2f/settings/finishregister",
   "message":{
      "Exception":"Exception",
      "Message":"Argument 1 passed to OCA\\TwoFactorU2F\\Controller\\SettingsController::finishRegister() must be ofthe type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 170",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/html/lib/private/AppFramework/App.php",
            "line":125,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\TwoFactorU2F\\Controller\\SettingsController"
               },
               "finishRegister"
            ]
         },
         {
            "file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
            "line":47,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::",
            "args":[
               "OCA\\TwoFactorU2F\\Controller\\SettingsController",
               "finishRegister",
               {
                  "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
               },
               {
                  "_route":"twofactor_u2f.settings.finishRegister"
               }
            ]
         },
         {
            "function":"__invoke",
            "class":"OC\\AppFramework\\Routing\\RouteActionHandler",
            "type":"->",
            "args":[
               {
                  "_route":"twofactor_u2f.settings.finishRegister"
               }
            ]
         },
         {
            "file":"/var/www/html/lib/private/Route/Router.php",
            "line":299,
            "function":"call_user_func",
            "args":[
               {
                  "__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"
               },
               {
                  "_route":"twofactor_u2f.settings.finishRegister"
               }
            ]
         },
         {
            "file":"/var/www/html/lib/base.php",
            "line":1008,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->",
            "args":[
               "/apps/twofactor_u2f/settings/finishregister"
            ]
         },
         {
            "file":"/var/www/html/index.php",
            "line":38,
            "function":"handleRequest",
            "class":"OC",
            "type":"::",
            "args":[

            ]
         }
      ],
      "File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
      "Line":109,
      "Previous":{
         "Exception":"TypeError",
         "Message":"Argument 1 passed to OCA\\TwoFactorU2F\\Controller\\SettingsController::finishRegister() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 170",
         "Code":0,
         "Trace":[
            {
               "file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
               "line":170,
               "function":"finishRegister",
               "class":"OCA\\TwoFactorU2F\\Controller\\SettingsController",
               "type":"->",
               "args":[
                  null,
                  null,
                  "4c 6704622"
               ]
            },
            {
               "file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
               "line":99,
               "function":"executeController",
               "class":"OC\\AppFramework\\Http\\Dispatcher",
               "type":"->",
               "args":[
                  {
                     "__class__":"OCA\\TwoFactorU2F\\Controller\\SettingsController"
                  },
                  "finishRegister"
               ]
            },
            {
               "file":"/var/www/html/lib/private/AppFramework/App.php",
               "line":125,
               "function":"dispatch",
               "class":"OC\\AppFramework\\Http\\Dispatcher",
               "type":"->",
               "args":[
                  {
                     "__class__":"OCA\\TwoFactorU2F\\Controller\\SettingsController"
                  },
                  "finishRegister"
               ]
            },
            {
               "file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
               "line":47,
               "function":"main",
               "class":"OC\\AppFramework\\App",
               "type":"::",
               "args":[
                  "OCA\\TwoFactorU2F\\Controller\\SettingsController",
                  "finishRegister",
                  {
                     "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
                  },
                  {
                     "_route":"twofactor_u2f.settings.finishRegister"
                  }
               ]
            },
            {
               "function":"__invoke",
               "class":"OC\\AppFramework\\Routing\\RouteActionHandler",
               "type":"->",
               "args":[
                  {
                     "_route":"twofactor_u2f.settings.finishRegister"
                  }
               ]
            },
            {
               "file":"/var/www/html/lib/private/Route/Router.php",
               "line":299,
               "function":"call_user_func",
               "args":[
                  {
                     "__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"
                  },
                  {
                     "_route":"twofactor_u2f.settings.finishRegister"
                  }
               ]
            },
            {
               "file":"/var/www/html/lib/base.php",
               "line":1008,
               "function":"match",
               "class":"OC\\Route\\Router",
               "type":"->",
               "args":[
                  "/apps/twofactor_u2f/settings/finishregister"
               ]
            },
            {
               "file":"/var/www/html/index.php",
               "line":38,
               "function":"handleRequest",
               "class":"OC",
               "type":"::",
               "args":[

               ]
            }
         ],
         "File":"/var/www/html/custom_apps/twofactor_u2f/lib/Controller/SettingsController.php",
         "Line":66
      },
      "CustomMessage":"--"
   },
   "userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0",
   "version":"18.0.3.0"
}
```

### Server configuration

**Operating system**:
Docker image  sha256:5003078085a57cd7e40da225a77af363c0610b7e963b2d57bf868eec8503c986 
(ARM)

**Database:**
Docker image
 sha256:754a20b77cd8ec022c9a0de28ff3bdb2d4556c1186b64fcb9ab2816002671b3d 
postgres:11 (ARM)

**Version:** (see admin page)
Nextcloud 18.0.3

**List of activated apps:**
```
www-data@386119da3a3b:~/html$ php occ app:list
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**The content of config/config.php:**
```
ww-data@386119da3a3b:~/html$  php occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}
```

#### docker stack
```
version: '3'

services:
  db:
    image: postgres:11
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=***REMOVED SENSITIVE VALUE***
      - POSTGRES_PASSWORD=***REMOVED SENSITIVE VALUE***
      - POSTGRES_DB=notthis
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

  nextcloud:
    image: nextcloud:stable
    environment:
      - POSTGRES_USER=***REMOVED SENSITIVE VALUE***
      - POSTGRES_PASSWORD=***REMOVED SENSITIVE VALUE***
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db:5432
    volumes:
      - nextcloud:/var/www/html 
      - apps:/var/www/html/custom_apps 
      - config:/var/www/html/config 
      - data:/var/www/html/data 
    networks:
      - internal
      - external
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:${HOST}"
        traefik.port: 80
        traefik.docker.network: traefik-net
        traefik.frontend.headers.STSSeconds: 63072000
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.redirect.permanent: 'true'
        traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
        traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/


volumes:
  db_data:
  nextcloud:
  apps:
  config:
  data:


networks:
  external:
  internal:
    driver: overlay
    internal: true
  traefik-net:
    external: true
```
